import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist as Font } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const font = Font({
  subsets: ["latin"],
  variable: "--font-default",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${font.variable} bg-background text-foreground`}
    >
      <body>{children}</body>
    </html>
  );
}
